---
version: 2
jobs:
  build:
    docker:
      - image: library/docker:17
    working_directory: /tmp/build
    environment:
      DIND_IMAGE: localhost/docker-in-docker-circleci
      TEST_IMAGE: localhost/docker-in-docker-circleci-test
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: |
            set -x
            # build the docker container
            docker build --rm=false --tag ${DIND_IMAGE} .
            # start the docker-in-docker
            dind=$(docker run --privileged --name some-docker -d ${DIND_IMAGE})
            docker ps
            docker logs ${dind}

            # build the test container
            docker build --rm=false --tag ${TEST_IMAGE} test/.

            # run the test container against the dind
            test=$(docker run --rm --link ${dind} ${TEST_IMAGE})

