---
version: 2
jobs:
  build:
    docker:
      - image: library/docker:17
    working_directory: /tmp/build
    environment:
      DIND_IMAGE: localhost/docker-in-docker-circleci
      TEST_IMAGE: localhost/docker-in-docker-circleci-test
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          set -ex
          set -o pipefail

          # build the dind image
          docker build --rm=false --tag ${DIND_IMAGE} .

          # start the dind container
          dind=$(docker run --privileged -d ${DIND_IMAGE})

          # confirm it's running
          docker ps
          docker logs ${dind}

          # attempt to build a container inside it
          docker exec -it ${dind} docker build --tag ${TEST_IMAGE} test/.
          docker exec -it ${dind} docker images
          docker exec -it ${dind} docker run \
            -v /var/run/docker.sock:/var/run/docker.sock \
            ${TEST_IMAGE}

